# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         razor-agents
version:      2.84
version_from: lib/Razor2/Client/Version.pm
installdirs:  site
requires:
    Digest::SHA1:                  0
    File::Copy:                    0
    File::Spec:                    0
    Getopt::Long:                  0
    MIME::Base64:                  0
    Test::More:                    0
    Time::HiRes:                   0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
